### ISSUE TITLE
Tables cut off in live preview

### ISSUE THREAD

**Issue by ryadaj** [hydescarf/Obsidian-Theme-Mado-Miniflow#13]
Hi! Just noticed wide tables are cut off in live preview mode: <img width="1134" alt="Screen Shot 2022-08-25 at 12 15 23" src="https://user-images.githubusercontent.com/82765301/186717638-9b0cf74f-097e-4197-be69-e9d2d62af3bc.png">

But not in reading mode: <img width="973" alt="Screen Shot 2022-08-25 at 12 15 30" src="https://user-images.githubusercontent.com/82765301/186717941-97023882-a6db-4c58-a036-0e0dc9fb05c8.png">
 
Would it be possible to fix the live preview mode OR allow to set a `cssClass: wide` or `max` in front matter?

Thanks! :)

**Comment by hydescarf** [comment]
That's actually a common thing in the default theme, it's unfortunately not what I can fix. I mean I can, but it requires a lot of workarounds on other elements as well to align the whole thing properly.

In the meantime, try this snippet instead: https://github.com/efemkay/obsidian-modular-css-layout
I haven't try it yet, but it should give you the option to widen your table without affecting other elements (but a plugin seems to be a requirement).

I'll still look around for a solution though, not liking my long table as well but don't want to add a plugin, lol

**Comment by hydescarf** [comment]
I've got a snippet working!
You can try this out with frontmatter cssclass "table-auto" with the following CSS snippet:
```css

.table-auto.is-readable-line-width>div.markdown-preview-sizer.markdown-preview-section,
.table-auto.markdown-source-view.mod-cm6.is-readable-line-width .cm-editor .cm-contentContainer,
.table-auto.markdown-source-view.mod-cm6.is-readable-line-width .cm-editor .cm-contentContainer .cm-content{
	max-width:100%;
}
.table-auto.is-readable-line-width>div.markdown-preview-sizer.markdown-preview-section>div>*,
.table-auto.markdown-source-view.mod-cm6.is-readable-line-width .cm-editor .cm-contentContainer .cm-content .cm-line{
	max-width:830px;
	margin-inline:auto!important;
}
.table-auto.is-readable-line-width>div.markdown-preview-sizer.markdown-preview-section>div>table,
.table-auto.markdown-source-view.mod-cm6.is-readable-line-width .cm-editor .cm-contentContainer .cm-content table{
	max-width:100%;
	margin-inline:auto!important;
}
```

This will auto-widen the table in that note to its maximum content size, while preserving the other elements size.
I might integrate this into the theme in a later date after some code brush up, for now we'll go with this temporary fix.
