### ISSUE TITLE
[SUGGESTION] Hide nav-files-container scrollbar but keep functionality

### ISSUE THREAD

**Issue by GiuseppePitruzzella** [hydescarf/Obsidian-Theme-Mado-Miniflow#14]
When the number of files exceeds the size of the screen, an ugly design is created given by the presence of the scrollbar. I recommend to remove the scrollbar but keep its functionality.

**Comment by hydescarf** [comment]
I will leave it on as default as it's a part of the minimal accessibility. Users might need the visible scrollbar to immediately know if their navigation is expanded (and is overflowing) or not most of the time, compared to the static position of the other buttons.

That being said, I'll probably include this into Style Settings as well in the future.
Here's a workaround snippet for now
```css
.nav-files-container::-webkit-scrollbar-thumb {
	visibility:hidden;
}
.nav-files-container::-webkit-scrollbar-thumb:hover {
	visibility:initial;
}
```
and if you'd like to have all scrollbars to function the same, just use the following instead:
```css
::-webkit-scrollbar-thumb {
	visibility:hidden;
}
::-webkit-scrollbar-thumb:hover {
	visibility:initial;
}
```
