### ISSUE TITLE
[Feature Request] Add option to always show all buttons

### ISSUE THREAD

**Issue by Trikzon** [hydescarf/Obsidian-Theme-Mado-Miniflow#2]
I LOVE the look of this theme, but can't stand the only-visible-while-hovering buttons.

Could you add either an easily changeable option in the .css or compatibility with [obsidian-style-settings](https://github.com/mgmeyers/obsidian-style-settings) to add an option to always show all buttons?

**Comment by hydescarf** [comment]
It won't be easy, though I'm planning to restyle them in the near future (not the visibility, they stay hidden). I'll try to include a convenient way to disable them through user's snippets.  

Support for Style Settings will take a lot of time as I have to overhaul the elements, as this theme is a direct copy from the previous theme, not lots of things are bound together (link colors actually uses Obsidian's default color, which is similar to the folder color, but they aren't in sync)
I do plan to do it anyway, but may not come so soon.

If you need them immediately, I'll find a time this week and provide the code to disable them, ~~though they may look very weird as some of the collides to each other~~, actually might as well provide a way to disable the design just for them

**Comment by hydescarf** [comment]
As a workaround until I solve the issue, you may use the following code in a snippet file and adjust them as you like:
```css
/* Dock-Ribbon */
.workspace-ribbon{
	visibility:initial;
	position:initial;
	margin-top:35px;
	background:none!important;
}
.workspace-ribbon-collapse-btn,
.side-dock-actions,
.side-dock-settings{
	position:initial;
	opacity:1;
	padding:20px 6px;
}
.side-dock-settings{
	margin-bottom:40px;
	border:none;
}
.side-dock-settings:hover,
.side-dock-actions:hover{
	border:none;
}
.side-dock-ribbon-action{
	padding:10px 0;
}

/* Titlebar */
.mod-left-split,
.mod-right-split{
	padding-top:35px;
}
.titlebar-button-container{
	opacity:1!important;
}

/* Workspace tab */
.workspace-tab-header-container{
	position:initial;
	opacity:1;
	height:auto;
}

/* File Explorer buttons */
.mod-left-split .workspace-leaf-content[data-type="file-explorer"] .nav-header{
	position:initial;
	opacity:1;
}

.mod-left-split .workspace-leaf-content[data-type="file-explorer"] .nav-header .nav-buttons-container{
	flex-direction:initial;
}
```
