### ISSUE TITLE
Modifications via CSS snippet not applied to "Move to new Window"

### ISSUE THREAD

**Issue by nousernameavailableanymore** [hydescarf/Obsidian-Theme-Mado-Miniflow#28]
I made some customization to colors and text decorations via CSS snippets.
Those work fine in the "normal" window (live preview).

However, those changes are not applied when using "move to new window".
A new window opens, however, the default colors and settings are shown.
Some of those settings (the modified colors) can be made available in the new window, when adding the CSS lines at the end of the theme.css file instead of using a snippet in the snippet folder (basically copying the contents of the css snippet into the theme.css).

There seems to be a known issue with Obisidan. Not sure if this applies here:
https://forum.obsidian.md/t/themes-and-snippets-dont-load-on-new-windows/49285

**Comment by hydescarf** [comment]
Do you mind sharing your snippets over here? I can try to test the snippets and see what I can help out with.

**Comment by nousernameavailableanymore** [comment]
Sure.
I made some modifications to the color scheme and added some comments for me.
Most of the variables are defined in another .css file.

I also made everything bold, as I find it easier to read with Lexend Deca font.

Please be aware, I have no clue about css, I just copy trial and error 😅

```css
body{
	/* --accent-h: 210; */
	/* --accent-s: 93%; */
	/* --accent-l: 62%; */
	--accent-h: 254;
	--accent-s: 80%;
	--accent-l: 68%;
	
	--titlebar-background:var(--background-secondary);
	--titlebar-background-focused:var(--background-secondary);
	
	--background-modifier-hover:var(--color-base-hover);
	
	--bold-weight:var(--font-bold);
	--italic-color:var(--text-muted);
	--code-normal:var(--text-muted);
	--blockquote-color:var(--color-muted);
	
	--background-primary:var(--color-base-00);
	--background-secondary:var(--color-base-20);
	--checklist-done-color:var(--color-base-50);
	
	--icon-m:20px;
	--icon-l:20px;	
	--divider-width: 4px;
	/* --callout-padding:17px 17px; */
	/* --callout-content-padding:0 12px 0 27px; */
	
	/* --embed-padding:13px 23px; */
	/* --list-indent:37px; */
	
	--header-height:43px;
	--tab-stacked-header-width:53px;
	
	
	/* custom */
	--border:0px solid var(--tab-outline-color);
	--button-radius:4px;
	--panel-radius:8px;
	--window-radius:23px;
	--button-padding-icon:7px;
	--button-padding-long:7px 15px;
	
	--background-fourth:var(--color-base-00-0);
	--background-fifth:var(--color-base-20-0);
	--panel-shadow:0 1px 3px var(--color-base-shadow);
	--panel-shadow-hover:0 3px 5px var(--color-base-shadow-hover);
	--window-shadow:0 0 9px var(--color-base-shadow-hover);
	--window-shadow-left:-4px 0 5px var(--color-base-shadow-hover);
	--window-shadow-right:4px 0 5px var(--color-base-shadow-hover);
	
	--sidebar-size-left:270px;
	--sidebar-size-right:270px;
	
	
	--color-strikethrough:var(--text-faint);
	--italic-color:var(--color-italic);
	--inline-code-color:var(--color-red);
	--indentation-guide-color: var(--sne-gold-trans3);
	--button-padding-long: 5px 1px !important; 
	
	
}
body.is-translucent{
	--background-primary:var(--color-base-00-trans);
	--background-secondary:var(--color-base-20-trans);
	--background-fourth:var(--color-base-00-0-trans);
}
body.toggle-tab-height{
	--header-height:35px;
}

.theme-dark,
.is-mobile.theme-dark,
.is-tablet.theme-dark{
	--color-base-00: #242618; /* Hintergrund Hauptfenster */
	--color-base-10: var(--sne-code); /* Code snippet Hintergrund */
	
	--color-base-05: var(--sne-rahmen); /* zb. Hintergrundfarbe gehoverter Tabs */
	--color-base-20: #1e2014; /* restlicher Hintergrund außenrum */
	
	
	--color-base-00-trans:hsla(215, 17%, 19%, 0.5); /*for transparency background*/
	--color-base-20-trans:hsla(214, 24%, 15%, 0.5);
	--color-base-00-0:hsla(212, 17%, 22%, 0.9); /* very white */
	--color-base-20-0:hsla(207, 10%, 10%, 0.1); /* hovered version for above */
	--color-base-00-0-trans:hsla(212, 17%, 22%, 0.5);
	--color-base-shadow:hsla(207, 10%, 10%, 0.1); /* shadow */
	--color-base-shadow-hover:hsla(212, 17%, 0%, 0.3); /* shadow hover*/
	--color-base-hover:var(--color-base-05); /* hover*/
	
	--color-base-30: var(--sne-rahmen); /* horizontale Linie --- */
	--color-base-35: #000000;
	--color-base-40: var(--sne-rahmen);  /* Rahmen um Modals, also zb. Settings Fenster */
	--color-base-50: #126d0e; /* Bullet Points und nicht ausgewählte Tabs Text */
	--color-base-70: #126d0e90;	/* text-muted, so ziemlich alles, was sonst nicht ausgewählt ist */
	--color-base-100: var(--sne-text); /* text-normal color */
  
	--color-accent: hsl(calc(var(--accent-h) - 0), calc(var(--accent-s) + 13%), calc(var(--accent-l) + 3%));
	--color-accent-1: #;
	--color-accent-2: hsl(calc(var(--accent-h) - 0), calc(var(--accent-s) + 7%), calc(var(--accent-l) + 2%));

	--color-red:hsla(365, 90%, 65%, 1); /* Code Snippet Text Farbe */
	--color-muted: #126d0e99;
	--color-italic:hsla(215, 33%, 60%, 1);
	
	--color-highlight: #000000; /* for highlight text color */
	--text-highlight-bg: #000000; /* for highlight text underline color */
	--text-on-accent: var(--sne-gold-trans);
}
.theme-dark:is(.THT-background,.THT-underline-light){
	--color-highlight: #000000;
}

/* Gap inbetween panes */
		.workspace-split.mod-vertical.mod-root,
		.workspace-split.mod-vertical.mod-root .workspace-split:not(.mod-horizontal){
			gap:14px;
		}



/* Abstand Note zu rechter Rand */
		body:not(.is-mobile) .workspace:not(.is-right-sidedock-open) .workspace-split.mod-vertical.mod-root {
				padding-right: 14px;
				height: auto;
		}
	
	
	
/* Abstand Note Inhalt zum Header */
		.ͼ1 .cm-scroller {
			margin-top: -2em;
		}
		
	
	
	
	.clickable-icon {
			color: var(--icon-color) !Important;
		}
	


/* 
---------------------------------- 
ALLES BOLD 
-------------------------------------------------- 
*/
		body *, .app-container * {
			font-weight: bold;
		}
		
		

		/* ---- Dataview inline Queries in Überschriften nicht bold ---- */
		.HyperMD-header > span,
		.HyperMD-header > .dataview-inline > span {
			font-weight: normal;
		}
		
		/* ---- Dataview inline Queries in Überschriften im Preview Popup nicht bold ---- */
		:is(h1, h2, h3, h4, h5, h6) > .dataview-inline-query,
		:is(h1, h2, h3, h4, h5, h6) > .dataview-inline-query > span {
			font-weight: normal !Important;
		}
		
		
		/* --------- Supercharged Links in Headings nicht fett ------- */		
		.HyperMD-header > .cm-header > .data-link-text > span {
			font-weight: normal !important;
		}
		
		
		/* -------------- Dataview Tables ----------------- */
		.markdown-source-view.mod-cm6 .dataview.table-view-table .table-view-tbody td {
			font-weight: bold;
		}

		/* ---------------- YAML nicht fett ---------------- */
		.markdown-source-view .cm-hmd-frontmatter, code.language-yaml {
			font-weight: normal !Important;
		}


	
		
```

**Comment by hydescarf** [comment]
I think the problem lies on the specific character `.ͼ1` that caused the whole css to stop working on a new window. Removing that helps apply the other styles to the new window successfully.
The forum post you have linked also has that character in it, by the way.

As for why it does that:
https://discuss.codemirror.net/t/why-does-cm6-use-the-character-in-class-names/2821
> These are generated anonymous classes. You shouldn’t be typing them, because targeting them with CSS rules isn’t going to work—they aren’t stable across page loads.

So, for the solution, I'm not sure what you want to style with it, but try and change the following code:
```
/* Abstand Note Inhalt zum Header */
		.ͼ1 .cm-scroller {
			margin-top: -2em;
		}
```
to
```
/* Abstand Note Inhalt zum Header */
		.cm-scroller {
			margin-top: -2em;
		}
```

**Comment by nousernameavailableanymore** [comment]
Hmm, ok, that worked for the most part.
There were still some styles not applied, because they were in other CSS files, which also contained `.ͼ1` character.

While it did not seem to make any difference in the example above, the following example does not seem to work for me without the `.ͼ1` character.

This is for Live Preview

```css
		.ͼ1 .cm-content {
		  width: 95% !Important;
		  max-width: 750px;
		  margin-left: auto;
		  margin-right: auto;
		}
```
